// <auto-generated />
namespace GigHub.Migrations
{
	using System.CodeDom.Compiler;
	using System.Data.Entity.Migrations.Infrastructure;
	using System.Resources;

	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
	public sealed partial class InitialModel : IMigrationMetadata
	{
		private readonly ResourceManager Resources = new ResourceManager(typeof(InitialModel));

		string IMigrationMetadata.Id => "201606112130551_InitialModel";

		string IMigrationMetadata.Source => null;

		string IMigrationMetadata.Target => Resources.GetString("Target");
	}
}
